language: python
python: 2.7
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-unit
    - python: 2.7
      env: TOXENV=py27-lint
    - python: 2.7
      env: TOXENV=py27-func
    - python: pypy2.7-5.8.0
      env: TOXENV=pypy-unit
    - python: pypy2.7-5.8.0
      env: TOXENV=pypy-func
    - python: 2.7
      env: TOXENV=py27-wheel
    - python: 2.7
      env: TOXENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
